export const thaiTimezones = [
    { label: "(GMT-11:00) เวลานีอูเอ", value: "Pacific/Niue" },
    { label: "(GMT-11:00) เวลามาตรฐานซามัว", value: "Pacific/Pago_Pago" },
    { label: "(GMT-10:00) เวลาตาฮีตี", value: "Pacific/Tahiti" },
    { label: "(GMT-10:00) เวลามาตรฐานหมู่เกาะคุก", value: "Pacific/Rarotonga" },
    { label: "(GMT-10:00) เวลามาตรฐานฮาวาย-อะลูเชียน", value: "Pacific/Honolulu" },
    { label: "(GMT-10:00) เวลาฮาวาย-อะลูเชียน", value: "US/Aleutian" },
    { label: "(GMT-09:30) เวลามาร์เคซัส", value: "Pacific/Marquesas" },
    { label: "(GMT-09:00) เวลาแกมเบียร์", value: "Pacific/Gambier" },
    { label: "(GMT-09:00) เวลาอะแลสกา - จูโน", value: "America/Juneau" },
    { label: "(GMT-09:00) เวลาอะแลสกา - ซิตกา", value: "America/Sitka" },
    { label: "(GMT-09:00) เวลาอะแลสกา - นอม", value: "America/Nome" },
    { label: "(GMT-09:00) เวลาอะแลสกา - เมทลากาตละ", value: "America/Metlakatla" },
    { label: "(GMT-09:00) เวลาอะแลสกา - ยากูทัต", value: "America/Yakutat" },
    { label: "(GMT-09:00) เวลาอะแลสกา - แองเคอเรจ", value: "America/Anchorage" },
    { label: "(GMT-08:00) เวลาแปซิฟิกในอเมริกาเหนือ - ทิฮัวนา", value: "America/Tijuana" },
    { label: "(GMT-08:00) เวลาแปซิฟิกในอเมริกาเหนือ - ลอสแองเจลิส", value: "America/Los_Angeles" },
    { label: "(GMT-08:00) เวลาแปซิฟิกในอเมริกาเหนือ - แวนคูเวอร์", value: "America/Vancouver" },
    { label: "(GMT-08:00) เวลาพิตแคร์น", value: "Pacific/Pitcairn" },
    { label: "(GMT-07:00) เวลาแถบภูเขาในอเมริกาเหนือ - ซิวดัดฮัวเรซ", value: "America/Ojinaga" }, // Close match or Ciudad_Juarez if available
    { label: "(GMT-07:00) เวลาแถบภูเขาในอเมริกาเหนือ - เดนเวอร์", value: "America/Denver" },
    { label: "(GMT-07:00) เวลาแถบภูเขาในอเมริกาเหนือ - บอยซี", value: "America/Boise" },
    { label: "(GMT-07:00) เวลาแถบภูเขาในอเมริกาเหนือ - อ่าวแคมบริดจ์", value: "America/Cambridge_Bay" },
    { label: "(GMT-07:00) เวลาแถบภูเขาในอเมริกาเหนือ - อินูวิก", value: "America/Inuvik" },
    { label: "(GMT-07:00) เวลาแถบภูเขาในอเมริกาเหนือ - เอดมันตัน", value: "America/Edmonton" },
    { label: "(GMT-07:00) เวลามาตรฐานแถบภูเขาในอเมริกาเหนือ - ดอว์สัน ครีก", value: "America/Dawson_Creek" },
    { label: "(GMT-07:00) เวลามาตรฐานแถบภูเขาในอเมริกาเหนือ - ฟอร์ตเนลสัน", value: "America/Fort_Nelson" },
    { label: "(GMT-07:00) เวลามาตรฐานแถบภูเขาในอเมริกาเหนือ - ฟินิกซ์", value: "America/Phoenix" },
    { label: "(GMT-07:00) เวลามาตรฐานแปซิฟิกเม็กซิโก - มาซาทลาน", value: "America/Mazatlan" },
    { label: "(GMT-07:00) เวลามาตรฐานแปซิฟิกเม็กซิโก - เอร์โมซีโย", value: "America/Hermosillo" },
    { label: "(GMT-07:00) เวลายูคอน - ดอว์สัน", value: "America/Dawson" },
    { label: "(GMT-07:00) เวลายูคอน - ไวต์ฮอร์ส", value: "America/Whitehorse" },
    { label: "(GMT-06:00) เวลากาลาปาโกส", value: "Pacific/Galapagos" },
    { label: "(GMT-06:00) เวลาตอนกลางในอเมริกาเหนือ - ชิคาโก", value: "America/Chicago" },
    { label: "(GMT-06:00) เวลาตอนกลางในอเมริกาเหนือ - เซนเตอร์, นอร์ทดาโคตา", value: "America/North_Dakota/Center" },
    { label: "(GMT-06:00) เวลาตอนกลางในอเมริกาเหนือ - เทลล์ซิตี, อินดีแอนา", value: "America/Indiana/Tell_City" },
    { label: "(GMT-06:00) เวลาตอนกลางในอเมริกาเหนือ - นอกซ์, อินดีแอนา", value: "America/Indiana/Knox" },
    { label: "(GMT-06:00) เวลาตอนกลางในอเมริกาเหนือ - นิวเซเลม, นอร์ทดาโคตา", value: "America/North_Dakota/New_Salem" },
    { label: "(GMT-06:00) เวลาตอนกลางในอเมริกาเหนือ - โบลาห์, นอร์ทดาโคตา", value: "America/North_Dakota/Beulah" },
    { label: "(GMT-06:00) เวลาตอนกลางในอเมริกาเหนือ - มาตาโมรอส", value: "America/Matamoros" },
    { label: "(GMT-06:00) เวลาตอนกลางในอเมริกาเหนือ - เมโนมินี", value: "America/Menominee" },
    { label: "(GMT-06:00) เวลาตอนกลางในอเมริกาเหนือ - เรโซลูท", value: "America/Resolute" },
    { label: "(GMT-06:00) เวลาตอนกลางในอเมริกาเหนือ - แรงกินอินเล็ต", value: "America/Rankin_Inlet" },
    { label: "(GMT-06:00) เวลาตอนกลางในอเมริกาเหนือ - วินนิเพก", value: "America/Winnipeg" },
    { label: "(GMT-06:00) เวลาตอนกลางในอเมริกาเหนือ - โอจินากา", value: "America/Ojinaga" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - กัวเตมาลา", value: "America/Guatemala" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - คอสตาริกา", value: "America/Costa_Rica" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - ชีวาวา", value: "America/Chihuahua" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - เตกูซิกัลปา", value: "America/Tegucigalpa" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - บาเอียบันเดรัส", value: "America/Bahia_Banderas" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - เบลีซ", value: "America/Belize" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - มอนเตร์เรย์", value: "America/Monterrey" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - มานากัว", value: "America/Managua" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - เม็กซิโกซิตี", value: "America/Mexico_City" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - เมรีดา", value: "America/Merida" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - ริไจนา", value: "America/Regina" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - สวิฟต์เคอร์เรนต์", value: "America/Swift_Current" },
    { label: "(GMT-06:00) เวลามาตรฐานตอนกลางในอเมริกาเหนือ - เอลซัลวาดอร์", value: "America/El_Salvador" },
    { label: "(GMT-05:00) เวลาเกาะอีสเตอร์", value: "Pacific/Easter" },
    { label: "(GMT-05:00) เวลาคิวบา", value: "America/Havana" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - แกรนด์เติร์ก", value: "America/Grand_Turk" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - ดีทรอยต์", value: "America/Detroit" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - โทรอนโต", value: "America/Toronto" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - นิวยอร์ก", value: "America/New_York" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - ปอร์โตแปรงซ์", value: "America/Port-au-Prince" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - ปีเตอร์สเบิร์ก, อินดีแอนา", value: "America/Indiana/Petersburg" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - มอนติเซลโล, เคนตักกี", value: "America/Kentucky/Monticello" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - มาเรงโก, อินดีแอนา", value: "America/Indiana/Marengo" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - ลูส์วิลล์", value: "America/Louisville" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - วินเซนเนส, อินดีแอนา", value: "America/Indiana/Vincennes" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - วินาแมค, อินดีแอนา", value: "America/Indiana/Winamac" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - วีเวย์, อินดีแอนา", value: "America/Indiana/Vevay" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - อินเดียแนโพลิส", value: "America/Indiana/Indianapolis" },
    { label: "(GMT-05:00) เวลาทางตะวันออกในอเมริกาเหนือ - อีกวาลิต", value: "America/Iqaluit" },
    { label: "(GMT-05:00) เวลามาตรฐานโคลอมเบีย", value: "America/Bogota" },
    { label: "(GMT-05:00) เวลามาตรฐานทางตะวันออกในอเมริกาเหนือ - แคนคุน", value: "America/Cancun" },
    { label: "(GMT-05:00) เวลามาตรฐานทางตะวันออกในอเมริกาเหนือ - จาเมกา", value: "America/Jamaica" },
    { label: "(GMT-05:00) เวลามาตรฐานทางตะวันออกในอเมริกาเหนือ - ปานามา", value: "America/Panama" },
    { label: "(GMT-05:00) เวลามาตรฐานเปรู", value: "America/Lima" },
    { label: "(GMT-05:00) เวลามาตรฐานอาเกร - รีโอบรังโก", value: "America/Rio_Branco" },
    { label: "(GMT-05:00) เวลามาตรฐานอาเกร - เอรูเนเป", value: "America/Eirunepe" },
    { label: "(GMT-05:00) เวลาเอกวาดอร์", value: "America/Guayaquil" },
    { label: "(GMT-04:00) เวลากายอานา", value: "America/Guyana" },
    { label: "(GMT-04:00) เวลาโบลิเวีย", value: "America/La_Paz" },
    { label: "(GMT-04:00) เวลามาตรฐานแอตแลนติก - ซานโต โดมิงโก", value: "America/Santo_Domingo" },
    { label: "(GMT-04:00) เวลามาตรฐานแอตแลนติก - บาร์เบโดส", value: "America/Barbados" },
    { label: "(GMT-04:00) เวลามาตรฐานแอตแลนติก - เปอโตริโก", value: "America/Puerto_Rico" },
    { label: "(GMT-04:00) เวลามาตรฐานแอตแลนติก - มาร์ตินีก", value: "America/Martinique" },
    { label: "(GMT-04:00) เวลามาตรฐานแอมะซอน - กัมปูกรันดี", value: "America/Campo_Grande" },
    { label: "(GMT-04:00) เวลามาตรฐานแอมะซอน - กุยาบา", value: "America/Cuiaba" },
    { label: "(GMT-04:00) เวลามาตรฐานแอมะซอน - บัววีชตา", value: "America/Boa_Vista" },
    { label: "(GMT-04:00) เวลามาตรฐานแอมะซอน - ปอร์ตูเวลโย", value: "America/Porto_Velho" },
    { label: "(GMT-04:00) เวลามาตรฐานแอมะซอน - มาเนาส์", value: "America/Manaus" },
    { label: "(GMT-04:00) เวลาเวเนซุเอลา", value: "America/Caracas" },
    { label: "(GMT-04:00) เวลาแอตแลนติก - กูสเบย์", value: "America/Goose_Bay" },
    { label: "(GMT-04:00) เวลาแอตแลนติก - เกลซเบย์", value: "America/Glace_Bay" },
    { label: "(GMT-04:00) เวลาแอตแลนติก - ทูเล", value: "America/Thule" },
    { label: "(GMT-04:00) เวลาแอตแลนติก - เบอร์มิวดา", value: "Atlantic/Bermuda" },
    { label: "(GMT-04:00) เวลาแอตแลนติก - มองตัน", value: "America/Moncton" },
    { label: "(GMT-04:00) เวลาแอตแลนติก - แฮลิแฟกซ์", value: "America/Halifax" },
    { label: "(GMT-03:30) เวลานิวฟันด์แลนด์", value: "America/St_Johns" },
    { label: "(GMT-03:00) เวลาโกไยเก", value: "America/Punta_Arenas" }, // Mismatch risk but close
    { label: "(GMT-03:00) เวลาชิลี", value: "America/Santiago" },
    { label: "(GMT-03:00) เวลาซูรินาเม", value: "America/Paramaribo" },
    { label: "(GMT-03:00) เวลาแซงปีแยร์และมีเกอลง", value: "America/Miquelon" },
    { label: "(GMT-03:00) เวลาปุนตาอาเรนัส", value: "America/Punta_Arenas" },
    { label: "(GMT-03:00) เวลาพาล์เมอร์", value: "Antarctica/Palmer" },
    { label: "(GMT-03:00) เวลาเฟรนช์เกียนา", value: "America/Cayenne" },
    { label: "(GMT-03:00) เวลามาตรฐานบราซิเลีย - ซันตาเรม", value: "America/Santarem" },
    { label: "(GMT-03:00) เวลามาตรฐานบราซิเลีย - เซาเปาลู", value: "America/Sao_Paulo" },
    { label: "(GMT-03:00) เวลามาตรฐานบราซิเลีย - บาเยีย", value: "America/Bahia" },
    { label: "(GMT-03:00) เวลามาตรฐานบราซิเลีย - เบเลง", value: "America/Belem" },
    { label: "(GMT-03:00) เวลามาตรฐานบราซิเลีย - ฟอร์ตาเลซา", value: "America/Fortaleza" },
    { label: "(GMT-03:00) เวลามาตรฐานบราซิเลีย - มาเซโอ", value: "America/Maceio" },
    { label: "(GMT-03:00) เวลามาตรฐานบราซิเลีย - เรซีเฟ", value: "America/Recife" },
    { label: "(GMT-03:00) เวลามาตรฐานบราซิเลีย - อารากัวนา", value: "America/Araguaina" },
    { label: "(GMT-03:00) เวลามาตรฐานปารากวัย", value: "America/Asuncion" },
    { label: "(GMT-03:00) เวลามาตรฐานหมู่เกาะฟอล์กแลนด์", value: "Atlantic/Stanley" },
    { label: "(GMT-03:00) เวลามาตรฐานอาร์เจนตินา - กาตามาร์กา", value: "America/Catamarca" },
    { label: "(GMT-03:00) เวลามาตรฐานอาร์เจนตินา - คอร์โดบา", value: "America/Cordoba" },
    { label: "(GMT-03:00) เวลามาตรฐานอาร์เจนตินา - จูจิว", value: "America/Jujuy" },
    { label: "(GMT-03:00) เวลามาตรฐานอาร์เจนตินา - ซันลูอิส", value: "America/Argentina/San_Luis" },
    { label: "(GMT-03:00) เวลามาตรฐานอาร์เจนตินา - ซัลตา", value: "America/Argentina/Salta" },
    { label: "(GMT-03:00) เวลามาตรฐานอาร์เจนตินา - ซานฮวน", value: "America/Argentina/San_Juan" },
    { label: "(GMT-03:00) เวลามาตรฐานอาร์เจนตินา - ทูคูแมน", value: "America/Argentina/Tucuman" },
    { label: "(GMT-03:00) เวลามาตรฐานอาร์เจนตินา - บัวโนสไอเรส", value: "America/Argentina/Buenos_Aires" },
    { label: "(GMT-03:00) เวลามาตรฐานอาร์เจนตินา - เมนดูซา", value: "America/Argentina/Mendoza" },
    { label: "(GMT-03:00) เวลามาตรฐานอาร์เจนตินา - ริโอกาลเลกอส", value: "America/Argentina/Rio_Gallegos" },
    { label: "(GMT-03:00) เวลามาตรฐานอาร์เจนตินา - ลาริโอจา", value: "America/Argentina/La_Rioja" },
    { label: "(GMT-03:00) เวลามาตรฐานอาร์เจนตินา - อูชูเอีย", value: "America/Argentina/Ushuaia" },
    { label: "(GMT-03:00) เวลามาตรฐานอุรุกวัย", value: "America/Montevideo" },
    { label: "(GMT-03:00) เวลาโรธีรา", value: "Antarctica/Rothera" },
    { label: "(GMT-02:00) เวลากอดแธบ", value: "America/Nuuk" },
    { label: "(GMT-02:00) เวลาเซาท์จอร์เจีย", value: "Atlantic/South_Georgia" },
    { label: "(GMT-02:00) เวลามาตรฐานหมู่เกาะเฟอร์นันโด", value: "Atlantic/Noronha" }, // Fernando de Noronha
    { label: "(GMT-02:00) เวลาสกอเรสไบซันด์", value: "America/Scoresbysund" },
    { label: "(GMT-01:00) เวลามาตรฐานเคปเวิร์ด", value: "Atlantic/Cape_Verde" },
    { label: "(GMT-01:00) เวลาอะโซร์ส", value: "Atlantic/Azores" },
    { label: "(GMT+00:00) เวลาโทรล", value: "Antarctica/Troll" },
    { label: "(GMT+00:00) เวลามาตรฐานกรีนิช", value: "Etc/GMT" },
    { label: "(GMT+00:00) เวลามาตรฐานกรีนิช - เซาตูเม", value: "Africa/Sao_Tome" },
    { label: "(GMT+00:00) เวลามาตรฐานกรีนิช - ดานมาร์กสฮาวน์", value: "America/Danmarkshavn" },
    { label: "(GMT+00:00) เวลามาตรฐานกรีนิช - บิสเซา", value: "Africa/Bissau" },
    { label: "(GMT+00:00) เวลามาตรฐานกรีนิช - มันโรเวีย", value: "Africa/Monrovia" },
    { label: "(GMT+00:00) เวลามาตรฐานกรีนิช - เรคยาวิก", value: "Atlantic/Reykjavik" },
    { label: "(GMT+00:00) เวลามาตรฐานกรีนิช - อาบีจาน", value: "Africa/Abidjan" },
    { label: "(GMT+00:00) เวลายุโรปตะวันตก - คะเนรี", value: "Atlantic/Canary" },
    { label: "(GMT+00:00) เวลายุโรปตะวันตก - แฟโร", value: "Atlantic/Faroe" },
    { label: "(GMT+00:00) เวลายุโรปตะวันตก - มาเดรา", value: "Atlantic/Madeira" },
    { label: "(GMT+00:00) เวลายุโรปตะวันตก - ลิสบอน", value: "Europe/Lisbon" },
    { label: "(GMT+00:00) เวลาสหราชอาณาจักร", value: "Europe/London" },
    { label: "(GMT+00:00) เวลาสากลเชิงพิกัด", value: "UTC" },
    { label: "(GMT+00:00) เวลาไอร์แลนด์", value: "Europe/Dublin" },
    { label: "(GMT+01:00) เวลาซาฮาราตะวันตก", value: "Africa/El_Aaiun" },
    { label: "(GMT+01:00) เวลามาตรฐานยุโรปกลาง - ตูนิส", value: "Africa/Tunis" },
    { label: "(GMT+01:00) เวลามาตรฐานยุโรปกลาง - แอลเจียร์", value: "Africa/Algiers" },
    { label: "(GMT+01:00) เวลาโมร็อกโก", value: "Africa/Casablanca" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - โคเปนเฮเกน", value: "Europe/Copenhagen" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - ซูริค", value: "Europe/Zurich" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - เซวตา", value: "Africa/Ceuta" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - ติรานา", value: "Europe/Tirane" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - บรัสเซลส์", value: "Europe/Brussels" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - บูดาเปส", value: "Europe/Budapest" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - เบลเกรด", value: "Europe/Belgrade" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - เบอร์ลิน", value: "Europe/Berlin" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - ปราก", value: "Europe/Prague" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - ปารีส", value: "Europe/Paris" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - มอลตา", value: "Europe/Malta" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - มาดริด", value: "Europe/Madrid" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - โมนาโก", value: "Europe/Monaco" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - ยิบรอลตาร์", value: "Europe/Gibraltar" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - โรม", value: "Europe/Rome" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - ลักเซมเบิร์ก", value: "Europe/Luxembourg" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - วอร์ซอ", value: "Europe/Warsaw" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - เวียนนา", value: "Europe/Vienna" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - สตอกโฮล์ม", value: "Europe/Stockholm" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - ออสโล", value: "Europe/Oslo" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - อันดอร์รา", value: "Europe/Andorra" },
    { label: "(GMT+01:00) เวลายุโรปกลาง - อัมสเตอดัม", value: "Europe/Amsterdam" },
    { label: "(GMT+01:00) เวลาแอฟริกาตะวันตก - ลากอส", value: "Africa/Lagos" },
    { label: "(GMT+01:00) เวลาแอฟริกาตะวันตก - เอ็นจาเมนา", value: "Africa/Ndjamena" },
    { label: "(GMT+02:00) เวลามาตรฐานยุโรปตะวันออก - คาลินิงกราด", value: "Europe/Kaliningrad" },
    { label: "(GMT+02:00) เวลามาตรฐานยุโรปตะวันออก - ตรีโปลี", value: "Africa/Tripoli" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - กาซา", value: "Asia/Gaza" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - คีชีเนา", value: "Europe/Chisinau" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - เคียฟ", value: "Europe/Kiev" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - ไคโร", value: "Africa/Cairo" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - โซเฟีย", value: "Europe/Sofia" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - ทาลลินน์", value: "Europe/Tallinn" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - นิโคเซีย", value: "Asia/Nicosia" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - บูคาเรส", value: "Europe/Bucharest" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - เบรุต", value: "Asia/Beirut" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - แฟมากุสตา", value: "Asia/Famagusta" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - ริกา", value: "Europe/Riga" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - วิลนีอุส", value: "Europe/Vilnius" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - เอเธนส์", value: "Europe/Athens" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - เฮบรอน", value: "Asia/Hebron" },
    { label: "(GMT+02:00) เวลายุโรปตะวันออก - เฮลซิงกิ", value: "Europe/Helsinki" },
    { label: "(GMT+02:00) เวลาอิสราเอล", value: "Asia/Jerusalem" },
    { label: "(GMT+02:00) เวลาแอฟริกากลาง - คาร์ทูม", value: "Africa/Khartoum" },
    { label: "(GMT+02:00) เวลาแอฟริกากลาง - จูบา", value: "Africa/Juba" },
    { label: "(GMT+02:00) เวลาแอฟริกากลาง - มาปูโต", value: "Africa/Maputo" },
    { label: "(GMT+02:00) เวลาแอฟริกากลาง - วินด์ฮุก", value: "Africa/Windhoek" },
    { label: "(GMT+02:00) เวลาแอฟริกาใต้", value: "Africa/Johannesburg" },
    { label: "(GMT+03:00) เวลาจอร์แดน", value: "Asia/Amman" },
    { label: "(GMT+03:00) เวลาซีเรีย", value: "Asia/Damascus" },
    { label: "(GMT+03:00) เวลามาตรฐานตุรกี", value: "Europe/Istanbul" },
    { label: "(GMT+03:00) เวลามาตรฐานมอสโก - คิรอฟ", value: "Europe/Kirov" },
    { label: "(GMT+03:00) เวลามาตรฐานมอสโก - ซิมเฟอโรโปล", value: "Europe/Simferopol" },
    { label: "(GMT+03:00) เวลามาตรฐานมอสโก - มอสโก", value: "Europe/Moscow" },
    { label: "(GMT+03:00) เวลามาตรฐานมอสโก - มินสก์", value: "Europe/Minsk" },
    { label: "(GMT+03:00) เวลามาตรฐานมอสโก - วอลโกกราด", value: "Europe/Volgograd" },
    { label: "(GMT+03:00) เวลามาตรฐานอาหรับ - กาตาร์", value: "Asia/Qatar" },
    { label: "(GMT+03:00) เวลามาตรฐานอาหรับ - แบกแดด", value: "Asia/Baghdad" },
    { label: "(GMT+03:00) เวลามาตรฐานอาหรับ - ริยาร์ด", value: "Asia/Riyadh" },
    { label: "(GMT+03:00) เวลาแอฟริกาตะวันออก", value: "Africa/Nairobi" },
    { label: "(GMT+03:30) เวลามาตรฐานอิหร่าน", value: "Asia/Tehran" },
    { label: "(GMT+04:00) เวลากัลฟ์", value: "Asia/Dubai" },
    { label: "(GMT+04:00) เวลาเซเชลส์", value: "Indian/Mahe" },
    { label: "(GMT+04:00) เวลามาตรฐานจอร์เจีย", value: "Asia/Tbilisi" },
    { label: "(GMT+04:00) เวลามาตรฐานซามารา - ซามารา", value: "Europe/Samara" },
    { label: "(GMT+04:00) เวลามาตรฐานซามารา - ซาราทอฟ", value: "Europe/Saratov" },
    { label: "(GMT+04:00) เวลามาตรฐานซามารา - อะลิยานอฟ", value: "Europe/Ulyanovsk" },
    { label: "(GMT+04:00) เวลามาตรฐานซามารา - แอสตราคาน", value: "Europe/Astrakhan" },
    { label: "(GMT+04:00) เวลามาตรฐานมอริเชียส", value: "Indian/Mauritius" },
    { label: "(GMT+04:00) เวลามาตรฐานอาเซอร์ไบจาน", value: "Asia/Baku" },
    { label: "(GMT+04:00) เวลามาตรฐานอาร์เมเนีย", value: "Asia/Yerevan" },
    { label: "(GMT+04:00) เวลาเรอูนียง", value: "Indian/Reunion" },
    { label: "(GMT+04:30) เวลาอัฟกานิสถาน", value: "Asia/Kabul" },
    { label: "(GMT+05:00) เวลาคาซัคสถาน - คอสตาเนย์", value: "Asia/Qostanay" },
    { label: "(GMT+05:00) เวลาคาซัคสถาน - ไคซีลอร์ดา", value: "Asia/Qyzylorda" },
    { label: "(GMT+05:00) เวลาคาซัคสถาน - อทีราว", value: "Asia/Atyrau" },
    { label: "(GMT+05:00) เวลาคาซัคสถาน - ออรัล", value: "Asia/Oral" },
    { label: "(GMT+05:00) เวลาคาซัคสถาน - อัคตาอู", value: "Asia/Aqtau" },
    { label: "(GMT+05:00) เวลาคาซัคสถาน - อัคโทบี", value: "Asia/Aqtobe" },
    { label: "(GMT+05:00) เวลาคาซัคสถาน - อัลมาตี", value: "Asia/Almaty" },
    { label: "(GMT+05:00) เวลาทาจิกิสถาน", value: "Asia/Dushanbe" },
    { label: "(GMT+05:00) เวลาเฟรนช์เซาเทิร์นและแอนตาร์กติก", value: "Indian/Kerguelen" },
    { label: "(GMT+05:00) เวลามอว์สัน", value: "Antarctica/Mawson" },
    { label: "(GMT+05:00) เวลามัลดีฟส์", value: "Indian/Maldives" },
    { label: "(GMT+05:00) เวลามาตรฐานเติร์กเมนิสถาน", value: "Asia/Ashgabat" },
    { label: "(GMT+05:00) เวลามาตรฐานปากีสถาน", value: "Asia/Karachi" },
    { label: "(GMT+05:00) เวลามาตรฐานเยคาเตรินบูร์ก", value: "Asia/Yekaterinburg" },
    { label: "(GMT+05:00) เวลามาตรฐานอุซเบกิสถาน - ซามาร์กานด์", value: "Asia/Samarkand" },
    { label: "(GMT+05:00) เวลามาตรฐานอุซเบกิสถาน - ทาชเคนต์", value: "Asia/Tashkent" },
    { label: "(GMT+05:00) เวลาวอสตอค", value: "Antarctica/Vostok" },
    { label: "(GMT+05:30) เวลาอินเดีย - โกลกาตา", value: "Asia/Kolkata" },
    { label: "(GMT+05:30) เวลาอินเดีย - โคลัมโบ", value: "Asia/Colombo" },
    { label: "(GMT+05:45) เวลาเนปาล", value: "Asia/Kathmandu" },
    { label: "(GMT+06:00) เวลาคีร์กีซสถาน", value: "Asia/Bishkek" },
    { label: "(GMT+06:00) เวลาภูฏาน", value: "Asia/Thimphu" },
    { label: "(GMT+06:00) เวลามหาสมุทรอินเดีย", value: "Indian/Chagos" },
    { label: "(GMT+06:00) เวลามาตรฐานบังกลาเทศ", value: "Asia/Dhaka" },
    { label: "(GMT+06:00) เวลามาตรฐานออมสค์", value: "Asia/Omsk" },
    { label: "(GMT+06:00) เวลาอุรุมชี", value: "Asia/Urumqi" },
    { label: "(GMT+06:30) เวลาพม่า", value: "Asia/Yangon" },
    { label: "(GMT+06:30) เวลาหมู่เกาะโคโคส", value: "Indian/Cocos" },
    { label: "(GMT+07:00) เวลาเกาะคริสต์มาส", value: "Indian/Christmas" },
    { label: "(GMT+07:00) เวลาเดวิส", value: "Antarctica/Davis" },
    { label: "(GMT+07:00) เวลามาตรฐานครัสโนยาสค์ - ครัสโนยาร์สก์", value: "Asia/Krasnoyarsk" },
    { label: "(GMT+07:00) เวลามาตรฐานครัสโนยาสค์ - ตอมสค์", value: "Asia/Tomsk" },
    { label: "(GMT+07:00) เวลามาตรฐานครัสโนยาสค์ - โนโวคุซเนตสค์", value: "Asia/Novokuznetsk" },
    { label: "(GMT+07:00) เวลามาตรฐานครัสโนยาสค์ - โนโวซิบิร์สก์", value: "Asia/Novosibirsk" },
    { label: "(GMT+07:00) เวลามาตรฐานครัสโนยาสค์ - บาร์เนาว์", value: "Asia/Barnaul" },
    { label: "(GMT+07:00) เวลามาตรฐานฮอฟด์", value: "Asia/Hovd" },
    { label: "(GMT+07:00) เวลาอินโดจีน - กรุงเทพ", value: "Asia/Bangkok" },
    { label: "(GMT+07:00) เวลาอินโดจีน - นครโฮจิมินห์", value: "Asia/Ho_Chi_Minh" },
    { label: "(GMT+07:00) เวลาอินโดนีเซียฝั่งตะวันตก - จาการ์ตา", value: "Asia/Jakarta" },
    { label: "(GMT+07:00) เวลาอินโดนีเซียฝั่งตะวันตก - พอนเทียนัก", value: "Asia/Pontianak" },
    { label: "(GMT+08:00) เวลาบรูไนดารุสซาลาม", value: "Asia/Brunei" },
    { label: "(GMT+08:00) เวลามาตรฐานจีน - เซี่ยงไฮ้", value: "Asia/Shanghai" },
    { label: "(GMT+08:00) เวลามาตรฐานจีน - มาเก๊า", value: "Asia/Macau" },
    { label: "(GMT+08:00) เวลามาตรฐานทางตะวันตกของออสเตรเลีย - เคซีย์", value: "Antarctica/Casey" },
    { label: "(GMT+08:00) เวลามาตรฐานทางตะวันตกของออสเตรเลีย - เพิร์ท", value: "Australia/Perth" },
    { label: "(GMT+08:00) เวลามาตรฐานไทเป", value: "Asia/Taipei" },
    { label: "(GMT+08:00) เวลามาตรฐานฟิลิปปินส์", value: "Asia/Manila" },
    { label: "(GMT+08:00) เวลามาตรฐานอีร์คุตสค์", value: "Asia/Irkutsk" },
    { label: "(GMT+08:00) เวลามาตรฐานอูลานบาตอร์ - อูลานบาตอร์", value: "Asia/Ulaanbaatar" },
    { label: "(GMT+08:00) เวลามาตรฐานฮ่องกง", value: "Asia/Hong_Kong" },
    { label: "(GMT+08:00) เวลามาเลเซีย - กัวลาลัมเปอร์", value: "Asia/Kuala_Lumpur" },
    { label: "(GMT+08:00) เวลามาเลเซีย - กูชิง", value: "Asia/Kuching" },
    { label: "(GMT+08:00) เวลาสิงคโปร์", value: "Asia/Singapore" },
    { label: "(GMT+08:00) เวลาอินโดนีเซียตอนกลาง", value: "Asia/Makassar" },
    { label: "(GMT+08:45) เวลามาตรฐานทางตะวันตกตอนกลางของออสเตรเลีย", value: "Australia/Eucla" },
    { label: "(GMT+09:00) เวลาติมอร์ตะวันออก", value: "Asia/Dili" },
    { label: "(GMT+09:00) เวลาปาเลา", value: "Pacific/Palau" },
    { label: "(GMT+09:00) เวลามาตรฐานเกาหลี - โซล", value: "Asia/Seoul" },
    { label: "(GMT+09:00) เวลามาตรฐานเกาหลี - เปียงยาง", value: "Asia/Pyongyang" },
    { label: "(GMT+09:00) เวลามาตรฐานญี่ปุ่น", value: "Asia/Tokyo" },
    { label: "(GMT+09:00) เวลามาตรฐานยาคุตสค์ - ชิตา", value: "Asia/Chita" },
    { label: "(GMT+09:00) เวลามาตรฐานยาคุตสค์ - ยาคุตสค์", value: "Asia/Yakutsk" },
    { label: "(GMT+09:00) เวลามาตรฐานยาคุตสค์ - ฮันดืยกา", value: "Asia/Khandyga" },
    { label: "(GMT+09:00) เวลาอินโดนีเซียฝั่งตะวันออก", value: "Asia/Jayapura" },
    { label: "(GMT+09:30) เวลามาตรฐานทางตอนกลางของออสเตรเลีย", value: "Australia/Adelaide" },
    { label: "(GMT+10:00) เวลาชามอร์โร", value: "Pacific/Guam" },
    { label: "(GMT+10:00) เวลาชุก", value: "Pacific/Chuuk" },
    { label: "(GMT+10:00) เวลาปาปัวนิวกินี", value: "Pacific/Port_Moresby" },
    { label: "(GMT+10:00) เวลามาตรฐานทางตะวันออกของออสเตรเลีย - บริสเบน", value: "Australia/Brisbane" },
    { label: "(GMT+10:00) เวลามาตรฐานทางตะวันออกของออสเตรเลีย - ลินดีแมน", value: "Australia/Lindeman" },
    { label: "(GMT+10:00) เวลามาตรฐานวลาดีวอสตอค - วลาดิโวสต็อก", value: "Asia/Vladivostok" },
    { label: "(GMT+10:00) เวลามาตรฐานวลาดีวอสตอค - อุสต์เนรา", value: "Asia/Ust-Nera" },
    { label: "(GMT+10:30) เวลาออสเตรเลียกลาง - โบรกเคนฮิลล์", value: "Australia/Broken_Hill" },
    { label: "(GMT+10:30) เวลาออสเตรเลียกลาง - แอดิเลด", value: "Australia/Adelaide" },
    { label: "(GMT+11:00) เวลาคอสไร", value: "Pacific/Kosrae" },
    { label: "(GMT+11:00) เวลาบูเกนวิลล์", value: "Pacific/Bougainville" },
    { label: "(GMT+11:00) เวลาโปนาเป", value: "Pacific/Pohnpei" },
    { label: "(GMT+11:00) เวลามาตรฐานนิวแคลิโดเนีย", value: "Pacific/Noumea" },
    { label: "(GMT+11:00) เวลามาตรฐานมากาดาน - ซเรดเนคโคลิมสก์", value: "Asia/Srednekolymsk" },
    { label: "(GMT+11:00) เวลามาตรฐานมากาดาน - ซาคาลิน", value: "Asia/Sakhalin" },
    { label: "(GMT+11:00) เวลามาตรฐานมากาดาน - มากาดาน", value: "Asia/Magadan" },
    { label: "(GMT+11:00) เวลามาตรฐานวานูอาตู", value: "Pacific/Efate" },
    { label: "(GMT+11:00) เวลาลอร์ดโฮว์", value: "Australia/Lord_Howe" },
    { label: "(GMT+11:00) เวลาหมู่เกาะโซโลมอน", value: "Pacific/Guadalcanal" },
    { label: "(GMT+11:00) เวลาออสเตรเลียตะวันออก - ซิดนีย์", value: "Australia/Sydney" },
    { label: "(GMT+11:00) เวลาออสเตรเลียตะวันออก - เมลเบิร์น", value: "Australia/Melbourne" },
    { label: "(GMT+11:00) เวลาออสเตรเลียตะวันออก - แมคควอรี", value: "Antarctica/Macquarie" },
    { label: "(GMT+11:00) เวลาออสเตรเลียตะวันออก - โฮบาร์ต", value: "Australia/Hobart" },
    { label: "(GMT+12:00) เวลาเกาะนอร์ฟอล์ก", value: "Pacific/Norfolk" },
    { label: "(GMT+12:00) เวลาเกาะเวก", value: "Pacific/Wake" },
    { label: "(GMT+12:00) เวลาตูวาลู", value: "Pacific/Funafuti" },
    { label: "(GMT+12:00) เวลานาอูรู", value: "Pacific/Nauru" },
    { label: "(GMT+12:00) เวลาเปโตรปัฟลอฟสค์-คัมชัตสกี - คามชัตกา", value: "Asia/Kamchatka" },
    { label: "(GMT+12:00) เวลาเปโตรปัฟลอฟสค์-คัมชัตสกี - อานาดีร์", value: "Asia/Anadyr" },
    { label: "(GMT+12:00) เวลามาตรฐานฟิจิ", value: "Pacific/Fiji" },
    { label: "(GMT+12:00) เวลาวาลลิสและฟุตูนา", value: "Pacific/Wallis" },
    { label: "(GMT+12:00) เวลาหมู่เกาะกิลเบิร์ต", value: "Pacific/Tarawa" },
    { label: "(GMT+12:00) เวลาหมู่เกาะมาร์แชลล์ - ควาจาเลน", value: "Pacific/Kwajalein" },
    { label: "(GMT+12:00) เวลาหมู่เกาะมาร์แชลล์ - มาจูโร", value: "Pacific/Majuro" },
    { label: "(GMT+13:00) เวลาโตเกเลา", value: "Pacific/Fakaofo" },
    { label: "(GMT+13:00) เวลานิวซีแลนด์", value: "Pacific/Auckland" },
    { label: "(GMT+13:00) เวลามาตรฐานตองกา", value: "Pacific/Tongatapu" },
    { label: "(GMT+13:00) เวลามาตรฐานอาปีอา", value: "Pacific/Apia" },
    { label: "(GMT+13:00) เวลาหมู่เกาะฟินิกซ์", value: "Pacific/Kanton" },
    { label: "(GMT+13:45) เวลาแชทัม", value: "Pacific/Chatham" },
    { label: "(GMT+14:00) เวลาหมู่เกาะไลน์", value: "Pacific/Kiritimati" }
];
